#An RNA string is a string formed from the alphabet containing 'A', 'C', 'G', and 'U'.
#Given a DNA string t corresponding to a coding strand, its transcribed RNA string u is formed by replacing all occurrences of 'T' in t with 'U' in u.
#Given: A DNA string t having length at most 1000 nt.
#Return: The transcribed RNA string of t.

#Sample data
#Input: GATGGAACTTGACTACGTAAATT
#Output: GAUGGAACUUGACUACGUAAAUU

"replace all T's with U's"

s ="TGCCACGGTGGTGCTGAAGAAACCGTCGTTCGTCTGATACCCTCCTACAGAAAGTGCGGATGTTCGGGAACACAGTAGGTAGTGGGAGGAACTGCTAGACTATCCGAGATACCGTTCGAGCAATCGGGTTTACCTTAATAGGTCTGGTGAACGGGCTTTAAAGAACGCCCGGGAGGGTGCAGCGTGAGCCACTACCAAAATACTGCCCAGCAAGGTGACAGCATTGTGGGTGCCTTTCCAAGGGTCCGCACTCCTCAAGACTGAACAACAACAAAGTCAAGTATACGACCGTAATACGAGCGGCTGAGCAATGGGCAGGCATTTGACTAGAGGATAGCCATCCACCTATCGTTCCTCTCCAGATGCTTCAATTTGACCGGCCTGACTGTCGACTCCTTCAAACGCAAGAATGCGGGAGGTCACTAAGGCCCATGACGATAATCGATGCCGGACGGTACAGCGTCTCTGACAGTTCCACCCCATGGCTTTTTATATGTCCATGGAAGACCCATTAAACGGAGCTACCAATTCGGGTCTCGGTCGCTATAGGACCCATGCTACGATAGGGTTGCCATTATGGAGAGCTAGACTTGTCGGAGCCCCCCAACCTTGAGTGAGCAACCATAGATCGCAGAGCGAATGCATGATGTCCCCACCAACGATAACGAGGCTAGTGCTTTTTGGGTTGCGAAACGTGATTGGGTACTAAGTGGAGGCAGCGGGTATTAAGGTGTAATTGATGAGGGCAGCCCTTTATGGTGCGCGCGGTGGATATGATGACAGCTTAGAACTCAAGAACGGGCACCCTATCATATTCGCGGATTGGTAGCTATAGCCCAGTCACGGGCTAGCTACAGCTCGTCCTTGCAACCCCTCTGGTTCTTCGACGTACAGACGATTTCCTAGCGGTATACCGTAGTGGACTGAAG"

a= split(s)
new_= ''.join(a)
#print(new_)

print(new_.replace("T", "U"))

#print(type(new_))

#print(split_sequence)

#print(split_sequence.replace("T", "U"))
